insert into manufacturer (id, name, updated) values (1, 'nec', '2017-07-26 15:16:19');
insert into manufacturer (id, name, updated) values (2, 'vestibulum sagittis', '2017-02-13 13:12:46');
insert into manufacturer (id, name, updated) values (3, 'vitae ipsum aliquam', '2017-08-27 11:18:17');
insert into manufacturer (id, name, updated) values (4, 'platea', '2017-05-10 18:26:13');
insert into manufacturer (id, name, updated) values (5, 'donec', '2017-01-22 10:41:52');
insert into manufacturer (id, name, updated) values (6, 'lacus morbi', '2017-09-13 16:28:19');
insert into manufacturer (id, name, updated) values (7, 'odio condimentum id', '2017-09-24 14:00:16');
insert into manufacturer (id, name, updated) values (8, 'maecenas ut massa', '2017-10-10 20:22:05');
insert into manufacturer (id, name, updated) values (9, 'at turpis', '2017-02-11 21:47:44');
insert into manufacturer (id, name, updated) values (10, 'magnis dis', '2017-05-23 22:24:59');
insert into manufacturer (id, name, updated) values (11, 'neque aenean auctor', '2017-04-29 14:04:28');
insert into manufacturer (id, name, updated) values (12, 'curae', '2017-06-09 16:54:30');
insert into manufacturer (id, name, updated) values (13, 'est et tempus', '2017-01-21 15:44:42');
insert into manufacturer (id, name, updated) values (14, 'lorem ipsum', '2017-12-11 21:31:55');
insert into manufacturer (id, name, updated) values (15, 'semper', '2017-04-24 10:00:47');
insert into manufacturer (id, name, updated) values (16, 'adipiscing elit proin', '2017-04-29 21:12:52');
insert into manufacturer (id, name, updated) values (17, 'pede libero', '2017-06-22 00:37:58');
insert into manufacturer (id, name, updated) values (18, 'nibh in', '2017-05-26 08:27:03');
insert into manufacturer (id, name, updated) values (19, 'nam tristique', '2017-07-01 08:08:48');
insert into manufacturer (id, name, updated) values (20, 'sed lacus morbi', '2017-04-28 14:59:36');
insert into manufacturer (id, name, updated) values (21, 'platea dictumst morbi', '2017-08-15 10:49:39');
insert into manufacturer (id, name, updated) values (22, 'ultrices aliquet maecenas', '2017-12-16 16:46:35');
insert into manufacturer (id, name, updated) values (23, 'sed vel enim', '2017-11-09 01:15:28');
insert into manufacturer (id, name, updated) values (24, 'pede morbi porttitor', '2018-01-05 20:16:59');
insert into manufacturer (id, name, updated) values (25, 'suspendisse', '2017-06-04 16:01:40');
insert into manufacturer (id, name, updated) values (26, 'metus aenean', '2017-12-19 18:02:51');
insert into manufacturer (id, name, updated) values (27, 'ante ipsum', '2017-09-04 13:57:04');
insert into manufacturer (id, name, updated) values (28, 'purus eu magna', '2017-06-13 04:07:53');
insert into manufacturer (id, name, updated) values (29, 'cubilia', '2017-10-14 08:30:35');
insert into manufacturer (id, name, updated) values (30, 'tellus', '2017-06-20 14:07:16');
insert into manufacturer (id, name, updated) values (31, 'iaculis diam erat', '2017-05-24 09:20:59');
insert into manufacturer (id, name, updated) values (32, 'lobortis sapien', '2017-07-15 05:34:45');
insert into manufacturer (id, name, updated) values (33, 'amet lobortis sapien', '2017-02-04 00:24:56');
insert into manufacturer (id, name, updated) values (34, 'ligula', '2017-08-28 11:53:40');
insert into manufacturer (id, name, updated) values (35, 'eros', '2017-05-07 22:16:24');
insert into manufacturer (id, name, updated) values (36, 'venenatis', '2017-05-31 15:31:47');
insert into manufacturer (id, name, updated) values (37, 'ac tellus semper', '2017-07-07 10:46:55');
insert into manufacturer (id, name, updated) values (38, 'eget eros', '2017-08-30 10:47:53');
insert into manufacturer (id, name, updated) values (39, 'in porttitor', '2017-12-03 01:05:56');
insert into manufacturer (id, name, updated) values (40, 'iaculis', '2017-12-25 05:57:29');
insert into manufacturer (id, name, updated) values (41, 'justo etiam', '2017-01-11 06:40:56');
insert into manufacturer (id, name, updated) values (42, 'amet lobortis sapien', '2017-05-13 02:42:55');
insert into manufacturer (id, name, updated) values (43, 'donec', '2017-11-12 18:33:17');
insert into manufacturer (id, name, updated) values (44, 'amet turpis elementum', '2017-01-14 09:27:33');
insert into manufacturer (id, name, updated) values (45, 'nec dui', '2017-09-16 11:17:53');
insert into manufacturer (id, name, updated) values (46, 'sed ante', '2017-11-03 00:05:29');
insert into manufacturer (id, name, updated) values (47, 'sapien iaculis', '2017-10-09 23:10:51');
insert into manufacturer (id, name, updated) values (48, 'non pretium quis', '2017-11-06 00:43:29');
insert into manufacturer (id, name, updated) values (49, 'consequat dui nec', '2017-07-03 05:43:10');
insert into manufacturer (id, name, updated) values (50, 'viverra dapibus', '2017-08-26 04:48:55');
insert into manufacturer (id, name, updated) values (51, 'quam fringilla rhoncus', '2017-08-03 22:56:03');
insert into manufacturer (id, name, updated) values (52, 'augue', '2017-07-26 07:20:21');
insert into manufacturer (id, name, updated) values (53, 'tincidunt', '2017-04-10 20:41:44');
insert into manufacturer (id, name, updated) values (54, 'in', '2017-11-02 20:50:52');
insert into manufacturer (id, name, updated) values (55, 'primis', '2017-06-08 11:05:04');
insert into manufacturer (id, name, updated) values (56, 'sed', '2017-01-09 05:21:32');
insert into manufacturer (id, name, updated) values (57, 'diam vitae quam', '2017-05-02 12:53:27');
insert into manufacturer (id, name, updated) values (58, 'in consequat', '2017-05-09 00:47:10');
insert into manufacturer (id, name, updated) values (59, 'erat', '2017-07-09 20:33:28');
insert into manufacturer (id, name, updated) values (60, 'in sapien iaculis', '2017-04-02 19:56:01');
insert into manufacturer (id, name, updated) values (61, 'tortor duis mattis', '2017-03-15 07:36:55');
insert into manufacturer (id, name, updated) values (62, 'justo', '2017-02-04 22:41:22');
insert into manufacturer (id, name, updated) values (63, 'lectus in quam', '2017-06-28 18:25:25');
insert into manufacturer (id, name, updated) values (64, 'accumsan felis', '2017-08-24 12:10:59');
insert into manufacturer (id, name, updated) values (65, 'erat tortor sollicitudin', '2017-06-14 07:03:48');
insert into manufacturer (id, name, updated) values (66, 'leo', '2017-06-22 02:20:10');
insert into manufacturer (id, name, updated) values (67, 'cursus vestibulum proin', '2017-12-16 12:08:13');
insert into manufacturer (id, name, updated) values (68, 'amet diam', '2017-10-09 19:41:10');
insert into manufacturer (id, name, updated) values (69, 'platea dictumst etiam', '2017-04-20 17:16:50');
insert into manufacturer (id, name, updated) values (70, 'tortor id', '2017-04-27 19:27:51');
insert into manufacturer (id, name, updated) values (71, 'dis parturient', '2017-11-24 09:47:55');
insert into manufacturer (id, name, updated) values (72, 'diam nam tristique', '2017-03-10 11:55:53');
insert into manufacturer (id, name, updated) values (73, 'consequat in', '2017-05-15 07:31:12');
insert into manufacturer (id, name, updated) values (74, 'in sapien', '2017-04-03 09:02:43');
insert into manufacturer (id, name, updated) values (75, 'sit amet eleifend', '2017-10-14 14:19:11');
insert into manufacturer (id, name, updated) values (76, 'quam', '2017-07-30 23:55:02');
insert into manufacturer (id, name, updated) values (77, 'integer aliquet', '2017-12-15 01:15:12');
insert into manufacturer (id, name, updated) values (78, 'a suscipit nulla', '2017-08-14 11:20:05');
insert into manufacturer (id, name, updated) values (79, 'platea', '2017-05-07 11:31:57');
insert into manufacturer (id, name, updated) values (80, 'suspendisse', '2017-11-30 02:53:37');
insert into manufacturer (id, name, updated) values (81, 'metus', '2017-03-14 22:55:40');
insert into manufacturer (id, name, updated) values (82, 'ipsum primis in', '2017-08-25 00:50:13');
insert into manufacturer (id, name, updated) values (83, 'pulvinar sed nisl', '2017-07-25 15:06:23');
insert into manufacturer (id, name, updated) values (84, 'tristique in tempus', '2017-12-20 14:56:53');
insert into manufacturer (id, name, updated) values (85, 'nascetur ridiculus mus', '2017-10-29 09:03:42');
insert into manufacturer (id, name, updated) values (86, 'a pede posuere', '2017-10-25 06:10:28');
insert into manufacturer (id, name, updated) values (87, 'ut', '2017-05-14 02:42:34');
insert into manufacturer (id, name, updated) values (88, 'lacinia', '2017-04-24 06:54:18');
insert into manufacturer (id, name, updated) values (89, 'morbi', '2017-07-14 21:41:04');
insert into manufacturer (id, name, updated) values (90, 'curabitur convallis duis', '2017-11-04 20:41:51');
insert into manufacturer (id, name, updated) values (91, 'leo rhoncus', '2017-06-03 20:58:11');
insert into manufacturer (id, name, updated) values (92, 'dictumst aliquam', '2017-01-12 20:29:14');
insert into manufacturer (id, name, updated) values (93, 'arcu', '2017-10-02 03:54:04');
insert into manufacturer (id, name, updated) values (94, 'sed magna at', '2017-05-12 03:07:55');
insert into manufacturer (id, name, updated) values (95, 'neque libero convallis', '2017-01-14 10:24:16');
insert into manufacturer (id, name, updated) values (96, 'blandit nam nulla', '2017-09-20 09:53:52');
insert into manufacturer (id, name, updated) values (97, 'quam pharetra magna', '2017-06-12 14:31:29');
insert into manufacturer (id, name, updated) values (98, 'at vulputate vitae', '2017-05-28 05:15:06');
insert into manufacturer (id, name, updated) values (99, 'ante', '2017-07-29 12:56:57');
insert into manufacturer (id, name, updated) values (100, 'molestie nibh', '2017-12-03 21:25:21');

insert into car (id, model, manufacturer_id) values (1, 'eget eleifend luctus', 90);
insert into car (id, model, manufacturer_id) values (2, 'duis mattis', 21);
insert into car (id, model, manufacturer_id) values (3, 'ut massa', 7);
insert into car (id, model, manufacturer_id) values (4, 'porta volutpat erat', 100);
insert into car (id, model, manufacturer_id) values (5, 'at diam', 12);
insert into car (id, model, manufacturer_id) values (6, 'quam fringilla', 82);
insert into car (id, model, manufacturer_id) values (7, 'lacus', 32);
insert into car (id, model, manufacturer_id) values (8, 'diam', 73);
insert into car (id, model, manufacturer_id) values (9, 'pulvinar', 62);
insert into car (id, model, manufacturer_id) values (10, 'at diam', 66);
insert into car (id, model, manufacturer_id) values (11, 'nulla', 45);
insert into car (id, model, manufacturer_id) values (12, 'dapibus dolor vel', 4);
insert into car (id, model, manufacturer_id) values (13, 'dolor', 100);
insert into car (id, model, manufacturer_id) values (14, 'vitae', 25);
insert into car (id, model, manufacturer_id) values (15, 'ipsum primis', 41);
insert into car (id, model, manufacturer_id) values (16, 'sagittis sapien cum', 96);
insert into car (id, model, manufacturer_id) values (17, 'cum', 70);
insert into car (id, model, manufacturer_id) values (18, 'etiam justo', 15);
insert into car (id, model, manufacturer_id) values (19, 'tellus', 65);
insert into car (id, model, manufacturer_id) values (20, 'nulla', 44);
insert into car (id, model, manufacturer_id) values (21, 'lectus', 7);
insert into car (id, model, manufacturer_id) values (22, 'morbi ut', 58);
insert into car (id, model, manufacturer_id) values (23, 'gravida sem', 68);
insert into car (id, model, manufacturer_id) values (24, 'facilisi cras', 9);
insert into car (id, model, manufacturer_id) values (25, 'sit amet consectetuer', 71);
insert into car (id, model, manufacturer_id) values (26, 'leo odio condimentum', 53);
insert into car (id, model, manufacturer_id) values (27, 'porta volutpat', 6);
insert into car (id, model, manufacturer_id) values (28, 'vel nulla', 73);
insert into car (id, model, manufacturer_id) values (29, 'dictumst aliquam augue', 31);
insert into car (id, model, manufacturer_id) values (30, 'ligula', 20);
insert into car (id, model, manufacturer_id) values (31, 'vestibulum', 70);
insert into car (id, model, manufacturer_id) values (32, 'justo', 68);
insert into car (id, model, manufacturer_id) values (33, 'curae duis faucibus', 57);
insert into car (id, model, manufacturer_id) values (34, 'aenean auctor', 10);
insert into car (id, model, manufacturer_id) values (35, 'ut blandit non', 40);
insert into car (id, model, manufacturer_id) values (36, 'ultrices libero', 54);
insert into car (id, model, manufacturer_id) values (37, 'mauris ullamcorper', 20);
insert into car (id, model, manufacturer_id) values (38, 'nonummy', 28);
insert into car (id, model, manufacturer_id) values (39, 'scelerisque mauris sit', 17);
insert into car (id, model, manufacturer_id) values (40, 'consequat lectus in', 93);
insert into car (id, model, manufacturer_id) values (41, 'eros', 67);
insert into car (id, model, manufacturer_id) values (42, 'odio donec vitae', 56);
insert into car (id, model, manufacturer_id) values (43, 'lobortis est', 47);
insert into car (id, model, manufacturer_id) values (44, 'sed', 68);
insert into car (id, model, manufacturer_id) values (45, 'nam dui proin', 76);
insert into car (id, model, manufacturer_id) values (46, 'sagittis dui vel', 53);
insert into car (id, model, manufacturer_id) values (47, 'maecenas', 11);
insert into car (id, model, manufacturer_id) values (48, 'venenatis lacinia aenean', 66);
insert into car (id, model, manufacturer_id) values (49, 'tincidunt ante', 86);
insert into car (id, model, manufacturer_id) values (50, 'vehicula consequat', 45);
insert into car (id, model, manufacturer_id) values (51, 'dui', 4);
insert into car (id, model, manufacturer_id) values (52, 'venenatis tristique', 9);
insert into car (id, model, manufacturer_id) values (53, 'orci luctus', 39);
insert into car (id, model, manufacturer_id) values (54, 'donec diam neque', 80);
insert into car (id, model, manufacturer_id) values (55, 'nisl', 81);
insert into car (id, model, manufacturer_id) values (56, 'risus dapibus augue', 71);
insert into car (id, model, manufacturer_id) values (57, 'nulla facilisi cras', 48);
insert into car (id, model, manufacturer_id) values (58, 'amet', 54);
insert into car (id, model, manufacturer_id) values (59, 'nulla mollis', 3);
insert into car (id, model, manufacturer_id) values (60, 'sit amet eleifend', 77);
insert into car (id, model, manufacturer_id) values (61, 'hac habitasse platea', 53);
insert into car (id, model, manufacturer_id) values (62, 'ultrices erat', 30);
insert into car (id, model, manufacturer_id) values (63, 'in', 19);
insert into car (id, model, manufacturer_id) values (64, 'nulla mollis molestie', 68);
insert into car (id, model, manufacturer_id) values (65, 'sapien', 66);
insert into car (id, model, manufacturer_id) values (66, 'cum sociis', 21);
insert into car (id, model, manufacturer_id) values (67, 'ante', 15);
insert into car (id, model, manufacturer_id) values (68, 'pede', 42);
insert into car (id, model, manufacturer_id) values (69, 'nisl duis', 23);
insert into car (id, model, manufacturer_id) values (70, 'vestibulum', 29);
insert into car (id, model, manufacturer_id) values (71, 'velit vivamus vel', 81);
insert into car (id, model, manufacturer_id) values (72, 'augue aliquam erat', 55);
insert into car (id, model, manufacturer_id) values (73, 'sollicitudin vitae', 54);
insert into car (id, model, manufacturer_id) values (74, 'nisl aenean lectus', 34);
insert into car (id, model, manufacturer_id) values (75, 'donec ut', 28);
insert into car (id, model, manufacturer_id) values (76, 'vehicula consequat morbi', 10);
insert into car (id, model, manufacturer_id) values (77, 'sagittis', 54);
insert into car (id, model, manufacturer_id) values (78, 'dolor morbi', 37);
insert into car (id, model, manufacturer_id) values (79, 'turpis nec', 40);
insert into car (id, model, manufacturer_id) values (80, 'nisl ut volutpat', 14);
insert into car (id, model, manufacturer_id) values (81, 'tortor', 56);
insert into car (id, model, manufacturer_id) values (82, 'facilisi', 18);
insert into car (id, model, manufacturer_id) values (83, 'congue vivamus metus', 77);
insert into car (id, model, manufacturer_id) values (84, 'elementum eu', 92);
insert into car (id, model, manufacturer_id) values (85, 'quam', 82);
insert into car (id, model, manufacturer_id) values (86, 'dolor sit', 59);
insert into car (id, model, manufacturer_id) values (87, 'enim leo rhoncus', 89);
insert into car (id, model, manufacturer_id) values (88, 'augue vestibulum rutrum', 36);
insert into car (id, model, manufacturer_id) values (89, 'eleifend quam', 17);
insert into car (id, model, manufacturer_id) values (90, 'ligula', 15);
insert into car (id, model, manufacturer_id) values (91, 'luctus', 44);
insert into car (id, model, manufacturer_id) values (92, 'tellus semper interdum', 24);
insert into car (id, model, manufacturer_id) values (93, 'pellentesque volutpat dui', 8);
insert into car (id, model, manufacturer_id) values (94, 'nulla sed', 28);
insert into car (id, model, manufacturer_id) values (95, 'nam', 12);
insert into car (id, model, manufacturer_id) values (96, 'posuere cubilia curae', 48);
insert into car (id, model, manufacturer_id) values (97, 'aenean fermentum donec', 90);
insert into car (id, model, manufacturer_id) values (98, 'nunc', 42);
insert into car (id, model, manufacturer_id) values (99, 'posuere cubilia curae', 28);
insert into car (id, model, manufacturer_id) values (100, 'nisl venenatis lacinia', 64);
insert into car (id, model, manufacturer_id) values (101, 'cubilia curae', 11);
insert into car (id, model, manufacturer_id) values (102, 'et', 90);
insert into car (id, model, manufacturer_id) values (103, 'erat', 66);
insert into car (id, model, manufacturer_id) values (104, 'vulputate nonummy', 25);
insert into car (id, model, manufacturer_id) values (105, 'et ultrices posuere', 58);
insert into car (id, model, manufacturer_id) values (106, 'sit amet consectetuer', 28);
insert into car (id, model, manufacturer_id) values (107, 'rhoncus', 63);
insert into car (id, model, manufacturer_id) values (108, 'enim blandit', 60);
insert into car (id, model, manufacturer_id) values (109, 'curabitur gravida nisi', 5);
insert into car (id, model, manufacturer_id) values (110, 'blandit', 25);
insert into car (id, model, manufacturer_id) values (111, 'phasellus', 7);
insert into car (id, model, manufacturer_id) values (112, 'augue aliquam erat', 61);
insert into car (id, model, manufacturer_id) values (113, 'nam congue', 44);
insert into car (id, model, manufacturer_id) values (114, 'at turpis a', 33);
insert into car (id, model, manufacturer_id) values (115, 'vel dapibus at', 14);
insert into car (id, model, manufacturer_id) values (116, 'mauris lacinia sapien', 59);
insert into car (id, model, manufacturer_id) values (117, 'in tempus', 20);
insert into car (id, model, manufacturer_id) values (118, 'proin', 84);
insert into car (id, model, manufacturer_id) values (119, 'in imperdiet et', 88);
insert into car (id, model, manufacturer_id) values (120, 'sit amet', 9);
insert into car (id, model, manufacturer_id) values (121, 'vel', 35);
insert into car (id, model, manufacturer_id) values (122, 'non pretium quis', 61);
insert into car (id, model, manufacturer_id) values (123, 'lorem integer tincidunt', 1);
insert into car (id, model, manufacturer_id) values (124, 'lacinia erat', 75);
insert into car (id, model, manufacturer_id) values (125, 'ut', 99);
insert into car (id, model, manufacturer_id) values (126, 'sed', 26);
insert into car (id, model, manufacturer_id) values (127, 'curabitur at ipsum', 41);
insert into car (id, model, manufacturer_id) values (128, 'leo odio', 59);
insert into car (id, model, manufacturer_id) values (129, 'nam ultrices', 11);
insert into car (id, model, manufacturer_id) values (130, 'ullamcorper', 6);
insert into car (id, model, manufacturer_id) values (131, 'sed sagittis nam', 42);
insert into car (id, model, manufacturer_id) values (132, 'lacinia erat', 92);
insert into car (id, model, manufacturer_id) values (133, 'dui', 8);
insert into car (id, model, manufacturer_id) values (134, 'volutpat convallis morbi', 1);
insert into car (id, model, manufacturer_id) values (135, 'morbi quis', 2);
insert into car (id, model, manufacturer_id) values (136, 'mollis molestie', 19);
insert into car (id, model, manufacturer_id) values (137, 'pulvinar nulla pede', 74);
insert into car (id, model, manufacturer_id) values (138, 'aliquam erat volutpat', 29);
insert into car (id, model, manufacturer_id) values (139, 'tellus in sagittis', 34);
insert into car (id, model, manufacturer_id) values (140, 'tristique in', 73);
insert into car (id, model, manufacturer_id) values (141, 'arcu sed', 18);
insert into car (id, model, manufacturer_id) values (142, 'lacinia erat', 98);
insert into car (id, model, manufacturer_id) values (143, 'nisl', 76);
insert into car (id, model, manufacturer_id) values (144, 'non ligula', 73);
insert into car (id, model, manufacturer_id) values (145, 'porttitor pede', 20);
insert into car (id, model, manufacturer_id) values (146, 'eros elementum', 95);
insert into car (id, model, manufacturer_id) values (147, 'dui proin leo', 83);
insert into car (id, model, manufacturer_id) values (148, 'nunc rhoncus', 52);
insert into car (id, model, manufacturer_id) values (149, 'ac', 60);
insert into car (id, model, manufacturer_id) values (150, 'augue', 39);
insert into car (id, model, manufacturer_id) values (151, 'eget tempus vel', 36);
insert into car (id, model, manufacturer_id) values (152, 'lacus morbi', 90);
insert into car (id, model, manufacturer_id) values (153, 'ullamcorper augue a', 22);
insert into car (id, model, manufacturer_id) values (154, 'augue vestibulum ante', 27);
insert into car (id, model, manufacturer_id) values (155, 'convallis morbi', 33);
insert into car (id, model, manufacturer_id) values (156, 'mauris vulputate elementum', 7);
insert into car (id, model, manufacturer_id) values (157, 'sit', 38);
insert into car (id, model, manufacturer_id) values (158, 'tempus vivamus in', 92);
insert into car (id, model, manufacturer_id) values (159, 'luctus nec', 82);
insert into car (id, model, manufacturer_id) values (160, 'vel lectus', 65);
insert into car (id, model, manufacturer_id) values (161, 'felis fusce', 20);
insert into car (id, model, manufacturer_id) values (162, 'sapien a', 81);
insert into car (id, model, manufacturer_id) values (163, 'ut nulla sed', 88);
insert into car (id, model, manufacturer_id) values (164, 'consequat varius integer', 14);
insert into car (id, model, manufacturer_id) values (165, 'justo', 98);
insert into car (id, model, manufacturer_id) values (166, 'consectetuer adipiscing elit', 94);
insert into car (id, model, manufacturer_id) values (167, 'et', 37);
insert into car (id, model, manufacturer_id) values (168, 'lobortis sapien sapien', 36);
insert into car (id, model, manufacturer_id) values (169, 'sit', 93);
insert into car (id, model, manufacturer_id) values (170, 'nisi at nibh', 93);
insert into car (id, model, manufacturer_id) values (171, 'nisi', 99);
insert into car (id, model, manufacturer_id) values (172, 'augue', 2);
insert into car (id, model, manufacturer_id) values (173, 'erat tortor', 85);
insert into car (id, model, manufacturer_id) values (174, 'ipsum primis in', 72);
insert into car (id, model, manufacturer_id) values (175, 'dui nec', 66);
insert into car (id, model, manufacturer_id) values (176, 'nascetur ridiculus', 92);
insert into car (id, model, manufacturer_id) values (177, 'donec posuere metus', 9);
insert into car (id, model, manufacturer_id) values (178, 'nonummy integer', 30);
insert into car (id, model, manufacturer_id) values (179, 'volutpat', 74);
insert into car (id, model, manufacturer_id) values (180, 'potenti in eleifend', 82);
insert into car (id, model, manufacturer_id) values (181, 'porttitor id consequat', 73);
insert into car (id, model, manufacturer_id) values (182, 'adipiscing elit proin', 6);
insert into car (id, model, manufacturer_id) values (183, 'nulla suscipit ligula', 93);
insert into car (id, model, manufacturer_id) values (184, 'et ultrices posuere', 39);
insert into car (id, model, manufacturer_id) values (185, 'pulvinar', 76);
insert into car (id, model, manufacturer_id) values (186, 'nec nisi', 56);
insert into car (id, model, manufacturer_id) values (187, 'donec', 34);
insert into car (id, model, manufacturer_id) values (188, 'felis', 55);
insert into car (id, model, manufacturer_id) values (189, 'tincidunt lacus at', 65);
insert into car (id, model, manufacturer_id) values (190, 'id massa id', 31);
insert into car (id, model, manufacturer_id) values (191, 'volutpat', 29);
insert into car (id, model, manufacturer_id) values (192, 'quam fringilla rhoncus', 13);
insert into car (id, model, manufacturer_id) values (193, 'est quam pharetra', 17);
insert into car (id, model, manufacturer_id) values (194, 'ante nulla', 44);
insert into car (id, model, manufacturer_id) values (195, 'vel dapibus at', 45);
insert into car (id, model, manufacturer_id) values (196, 'lectus', 41);
insert into car (id, model, manufacturer_id) values (197, 'molestie sed', 18);
insert into car (id, model, manufacturer_id) values (198, 'sed lacus morbi', 72);
insert into car (id, model, manufacturer_id) values (199, 'sollicitudin mi', 11);
insert into car (id, model, manufacturer_id) values (200, 'montes', 9);
insert into car (id, model, manufacturer_id) values (201, 'quis turpis sed', 28);
insert into car (id, model, manufacturer_id) values (202, 'luctus et', 25);
insert into car (id, model, manufacturer_id) values (203, 'diam', 51);
insert into car (id, model, manufacturer_id) values (204, 'vivamus tortor', 43);
insert into car (id, model, manufacturer_id) values (205, 'dictumst', 20);
insert into car (id, model, manufacturer_id) values (206, 'donec dapibus', 69);
insert into car (id, model, manufacturer_id) values (207, 'donec', 36);
insert into car (id, model, manufacturer_id) values (208, 'imperdiet sapien urna', 90);
insert into car (id, model, manufacturer_id) values (209, 'morbi porttitor', 8);
insert into car (id, model, manufacturer_id) values (210, 'ornare', 23);
insert into car (id, model, manufacturer_id) values (211, 'semper porta', 73);
insert into car (id, model, manufacturer_id) values (212, 'leo rhoncus sed', 42);
insert into car (id, model, manufacturer_id) values (213, 'magnis', 75);
insert into car (id, model, manufacturer_id) values (214, 'pede posuere nonummy', 97);
insert into car (id, model, manufacturer_id) values (215, 'velit nec', 77);
insert into car (id, model, manufacturer_id) values (216, 'dui vel', 59);
insert into car (id, model, manufacturer_id) values (217, 'pretium quis', 41);
insert into car (id, model, manufacturer_id) values (218, 'elementum ligula vehicula', 62);
insert into car (id, model, manufacturer_id) values (219, 'libero quis orci', 15);
insert into car (id, model, manufacturer_id) values (220, 'turpis nec', 42);
insert into car (id, model, manufacturer_id) values (221, 'non pretium quis', 31);
insert into car (id, model, manufacturer_id) values (222, 'ac', 35);
insert into car (id, model, manufacturer_id) values (223, 'mauris eget massa', 95);
insert into car (id, model, manufacturer_id) values (224, 'cum sociis natoque', 31);
insert into car (id, model, manufacturer_id) values (225, 'turpis enim blandit', 56);
insert into car (id, model, manufacturer_id) values (226, 'ut', 45);
insert into car (id, model, manufacturer_id) values (227, 'odio porttitor', 88);
insert into car (id, model, manufacturer_id) values (228, 'quam turpis', 27);
insert into car (id, model, manufacturer_id) values (229, 'sapien ut', 27);
insert into car (id, model, manufacturer_id) values (230, 'ultrices', 22);
insert into car (id, model, manufacturer_id) values (231, 'habitasse platea', 52);
insert into car (id, model, manufacturer_id) values (232, 'quis turpis', 27);
insert into car (id, model, manufacturer_id) values (233, 'tincidunt eu felis', 9);
insert into car (id, model, manufacturer_id) values (234, 'ligula in lacus', 31);
insert into car (id, model, manufacturer_id) values (235, 'vel', 89);
insert into car (id, model, manufacturer_id) values (236, 'quisque id justo', 89);
insert into car (id, model, manufacturer_id) values (237, 'duis', 41);
insert into car (id, model, manufacturer_id) values (238, 'libero', 6);
insert into car (id, model, manufacturer_id) values (239, 'orci luctus', 83);
insert into car (id, model, manufacturer_id) values (240, 'etiam', 51);
insert into car (id, model, manufacturer_id) values (241, 'ut', 53);
insert into car (id, model, manufacturer_id) values (242, 'in felis eu', 93);
insert into car (id, model, manufacturer_id) values (243, 'sit amet', 15);
insert into car (id, model, manufacturer_id) values (244, 'quam sapien varius', 81);
insert into car (id, model, manufacturer_id) values (245, 'nulla', 35);
insert into car (id, model, manufacturer_id) values (246, 'aliquet maecenas leo', 22);
insert into car (id, model, manufacturer_id) values (247, 'eleifend donec ut', 52);
insert into car (id, model, manufacturer_id) values (248, 'massa', 56);
insert into car (id, model, manufacturer_id) values (249, 'enim', 58);
insert into car (id, model, manufacturer_id) values (250, 'erat eros', 74);
insert into car (id, model, manufacturer_id) values (251, 'bibendum felis', 9);
insert into car (id, model, manufacturer_id) values (252, 'vestibulum sagittis', 34);
insert into car (id, model, manufacturer_id) values (253, 'augue vestibulum rutrum', 41);
insert into car (id, model, manufacturer_id) values (254, 'cum sociis', 92);
insert into car (id, model, manufacturer_id) values (255, 'auctor sed', 100);
insert into car (id, model, manufacturer_id) values (256, 'a ipsum integer', 17);
insert into car (id, model, manufacturer_id) values (257, 'libero nam dui', 32);
insert into car (id, model, manufacturer_id) values (258, 'at vulputate vitae', 40);
insert into car (id, model, manufacturer_id) values (259, 'sit amet nunc', 96);
insert into car (id, model, manufacturer_id) values (260, 'nulla', 45);
insert into car (id, model, manufacturer_id) values (261, 'dui nec', 41);
insert into car (id, model, manufacturer_id) values (262, 'varius ut', 88);
insert into car (id, model, manufacturer_id) values (263, 'semper sapien', 19);
insert into car (id, model, manufacturer_id) values (264, 'cras', 64);
insert into car (id, model, manufacturer_id) values (265, 'quam sollicitudin', 95);
insert into car (id, model, manufacturer_id) values (266, 'turpis donec posuere', 5);
insert into car (id, model, manufacturer_id) values (267, 'vel dapibus at', 81);
insert into car (id, model, manufacturer_id) values (268, 'risus dapibus augue', 76);
insert into car (id, model, manufacturer_id) values (269, 'nulla sed vel', 48);
insert into car (id, model, manufacturer_id) values (270, 'eu est', 28);
insert into car (id, model, manufacturer_id) values (271, 'semper porta', 27);
insert into car (id, model, manufacturer_id) values (272, 'suscipit ligula in', 28);
insert into car (id, model, manufacturer_id) values (273, 'mattis pulvinar nulla', 51);
insert into car (id, model, manufacturer_id) values (274, 'lorem ipsum dolor', 34);
insert into car (id, model, manufacturer_id) values (275, 'ultrices phasellus id', 97);
insert into car (id, model, manufacturer_id) values (276, 'pellentesque eget', 72);
insert into car (id, model, manufacturer_id) values (277, 'mus etiam vel', 49);
insert into car (id, model, manufacturer_id) values (278, 'duis', 88);
insert into car (id, model, manufacturer_id) values (279, 'porttitor pede', 16);
insert into car (id, model, manufacturer_id) values (280, 'viverra dapibus nulla', 7);
insert into car (id, model, manufacturer_id) values (281, 'tempus vivamus in', 65);
insert into car (id, model, manufacturer_id) values (282, 'maecenas tristique est', 36);
insert into car (id, model, manufacturer_id) values (283, 'massa', 11);
insert into car (id, model, manufacturer_id) values (284, 'donec odio justo', 93);
insert into car (id, model, manufacturer_id) values (285, 'integer', 77);
insert into car (id, model, manufacturer_id) values (286, 'aliquam lacus morbi', 82);
insert into car (id, model, manufacturer_id) values (287, 'tellus in sagittis', 28);
insert into car (id, model, manufacturer_id) values (288, 'imperdiet nullam orci', 78);
insert into car (id, model, manufacturer_id) values (289, 'non', 95);
insert into car (id, model, manufacturer_id) values (290, 'habitasse platea', 59);
insert into car (id, model, manufacturer_id) values (291, 'elementum nullam', 10);
insert into car (id, model, manufacturer_id) values (292, 'imperdiet sapien urna', 89);
insert into car (id, model, manufacturer_id) values (293, 'tempus sit', 18);
insert into car (id, model, manufacturer_id) values (294, 'parturient', 23);
insert into car (id, model, manufacturer_id) values (295, 'pellentesque', 4);
insert into car (id, model, manufacturer_id) values (296, 'odio elementum eu', 38);
insert into car (id, model, manufacturer_id) values (297, 'sit', 51);
insert into car (id, model, manufacturer_id) values (298, 'vel augue', 50);
insert into car (id, model, manufacturer_id) values (299, 'adipiscing molestie hendrerit', 63);
insert into car (id, model, manufacturer_id) values (300, 'ultrices libero non', 36);
insert into car (id, model, manufacturer_id) values (301, 'dictumst etiam', 85);
insert into car (id, model, manufacturer_id) values (302, 'in lectus', 59);
insert into car (id, model, manufacturer_id) values (303, 'nisl venenatis', 59);
insert into car (id, model, manufacturer_id) values (304, 'in', 45);
insert into car (id, model, manufacturer_id) values (305, 'proin leo odio', 87);
insert into car (id, model, manufacturer_id) values (306, 'porta', 44);
insert into car (id, model, manufacturer_id) values (307, 'integer non', 29);
insert into car (id, model, manufacturer_id) values (308, 'faucibus orci', 4);
insert into car (id, model, manufacturer_id) values (309, 'sollicitudin vitae', 16);
insert into car (id, model, manufacturer_id) values (310, 'diam neque vestibulum', 25);
insert into car (id, model, manufacturer_id) values (311, 'natoque penatibus', 79);
insert into car (id, model, manufacturer_id) values (312, 'lorem', 2);
insert into car (id, model, manufacturer_id) values (313, 'vel dapibus at', 39);
insert into car (id, model, manufacturer_id) values (314, 'sem praesent id', 48);
insert into car (id, model, manufacturer_id) values (315, 'eu massa donec', 41);
insert into car (id, model, manufacturer_id) values (316, 'cursus', 47);
insert into car (id, model, manufacturer_id) values (317, 'fermentum', 66);
insert into car (id, model, manufacturer_id) values (318, 'nulla dapibus dolor', 33);
insert into car (id, model, manufacturer_id) values (319, 'mus', 69);
insert into car (id, model, manufacturer_id) values (320, 'diam nam tristique', 67);
insert into car (id, model, manufacturer_id) values (321, 'sem', 44);
insert into car (id, model, manufacturer_id) values (322, 'hendrerit', 27);
insert into car (id, model, manufacturer_id) values (323, 'nulla elit', 93);
insert into car (id, model, manufacturer_id) values (324, 'in', 38);
insert into car (id, model, manufacturer_id) values (325, 'iaculis diam', 1);
insert into car (id, model, manufacturer_id) values (326, 'ligula pellentesque ultrices', 100);
insert into car (id, model, manufacturer_id) values (327, 'sit amet turpis', 50);
insert into car (id, model, manufacturer_id) values (328, 'habitasse platea', 96);
insert into car (id, model, manufacturer_id) values (329, 'lectus pellentesque', 32);
insert into car (id, model, manufacturer_id) values (330, 'porta volutpat quam', 19);
insert into car (id, model, manufacturer_id) values (331, 'amet', 79);
insert into car (id, model, manufacturer_id) values (332, 'vestibulum ante', 6);
insert into car (id, model, manufacturer_id) values (333, 'enim leo', 61);
insert into car (id, model, manufacturer_id) values (334, 'platea dictumst morbi', 76);
insert into car (id, model, manufacturer_id) values (335, 'odio', 20);
insert into car (id, model, manufacturer_id) values (336, 'dui luctus rutrum', 80);
insert into car (id, model, manufacturer_id) values (337, 'vivamus in felis', 100);
insert into car (id, model, manufacturer_id) values (338, 'odio donec', 62);
insert into car (id, model, manufacturer_id) values (339, 'cras pellentesque volutpat', 11);
insert into car (id, model, manufacturer_id) values (340, 'orci vehicula', 4);
insert into car (id, model, manufacturer_id) values (341, 'etiam', 15);
insert into car (id, model, manufacturer_id) values (342, 'risus', 89);
insert into car (id, model, manufacturer_id) values (343, 'vehicula', 45);
insert into car (id, model, manufacturer_id) values (344, 'neque', 64);
insert into car (id, model, manufacturer_id) values (345, 'odio condimentum id', 41);
insert into car (id, model, manufacturer_id) values (346, 'fusce', 27);
insert into car (id, model, manufacturer_id) values (347, 'lorem', 84);
insert into car (id, model, manufacturer_id) values (348, 'elit proin interdum', 60);
insert into car (id, model, manufacturer_id) values (349, 'amet turpis', 82);
insert into car (id, model, manufacturer_id) values (350, 'elementum', 60);
insert into car (id, model, manufacturer_id) values (351, 'phasellus sit amet', 94);
insert into car (id, model, manufacturer_id) values (352, 'sapien quis', 83);
insert into car (id, model, manufacturer_id) values (353, 'lectus in', 92);
insert into car (id, model, manufacturer_id) values (354, 'platea dictumst', 99);
insert into car (id, model, manufacturer_id) values (355, 'curae nulla', 82);
insert into car (id, model, manufacturer_id) values (356, 'justo', 61);
insert into car (id, model, manufacturer_id) values (357, 'tellus', 26);
insert into car (id, model, manufacturer_id) values (358, 'lacus', 43);
insert into car (id, model, manufacturer_id) values (359, 'lacinia aenean sit', 47);
insert into car (id, model, manufacturer_id) values (360, 'interdum', 44);
insert into car (id, model, manufacturer_id) values (361, 'cubilia curae donec', 58);
insert into car (id, model, manufacturer_id) values (362, 'lobortis sapien sapien', 57);
insert into car (id, model, manufacturer_id) values (363, 'nulla', 78);
insert into car (id, model, manufacturer_id) values (364, 'vestibulum vestibulum ante', 97);
insert into car (id, model, manufacturer_id) values (365, 'luctus', 50);
insert into car (id, model, manufacturer_id) values (366, 'habitasse platea dictumst', 79);
insert into car (id, model, manufacturer_id) values (367, 'et magnis', 69);
insert into car (id, model, manufacturer_id) values (368, 'est et tempus', 53);
insert into car (id, model, manufacturer_id) values (369, 'platea dictumst', 10);
insert into car (id, model, manufacturer_id) values (370, 'sapien dignissim vestibulum', 61);
insert into car (id, model, manufacturer_id) values (371, 'aenean', 91);
insert into car (id, model, manufacturer_id) values (372, 'hac habitasse', 38);
insert into car (id, model, manufacturer_id) values (373, 'interdum eu', 97);
insert into car (id, model, manufacturer_id) values (374, 'duis', 26);
insert into car (id, model, manufacturer_id) values (375, 'tempus vel', 79);
insert into car (id, model, manufacturer_id) values (376, 'est', 46);
insert into car (id, model, manufacturer_id) values (377, 'at turpis a', 77);
insert into car (id, model, manufacturer_id) values (378, 'varius integer', 2);
insert into car (id, model, manufacturer_id) values (379, 'luctus', 61);
insert into car (id, model, manufacturer_id) values (380, 'morbi', 89);
insert into car (id, model, manufacturer_id) values (381, 'molestie hendrerit at', 31);
insert into car (id, model, manufacturer_id) values (382, 'risus auctor sed', 66);
insert into car (id, model, manufacturer_id) values (383, 'non quam', 14);
insert into car (id, model, manufacturer_id) values (384, 'elit proin', 72);
insert into car (id, model, manufacturer_id) values (385, 'velit id pretium', 85);
insert into car (id, model, manufacturer_id) values (386, 'sem', 83);
insert into car (id, model, manufacturer_id) values (387, 'suspendisse accumsan tortor', 58);
insert into car (id, model, manufacturer_id) values (388, 'faucibus orci', 91);
insert into car (id, model, manufacturer_id) values (389, 'sit amet', 76);
insert into car (id, model, manufacturer_id) values (390, 'tincidunt eget', 13);
insert into car (id, model, manufacturer_id) values (391, 'pretium nisl', 58);
insert into car (id, model, manufacturer_id) values (392, 'adipiscing', 32);
insert into car (id, model, manufacturer_id) values (393, 'mi', 98);
insert into car (id, model, manufacturer_id) values (394, 'rutrum ac lobortis', 87);
insert into car (id, model, manufacturer_id) values (395, 'placerat', 51);
insert into car (id, model, manufacturer_id) values (396, 'enim', 90);
insert into car (id, model, manufacturer_id) values (397, 'blandit non', 31);
insert into car (id, model, manufacturer_id) values (398, 'justo', 68);
insert into car (id, model, manufacturer_id) values (399, 'eget vulputate', 70);
insert into car (id, model, manufacturer_id) values (400, 'varius ut', 96);
insert into car (id, model, manufacturer_id) values (401, 'nec molestie sed', 50);
insert into car (id, model, manufacturer_id) values (402, 'penatibus et magnis', 36);
insert into car (id, model, manufacturer_id) values (403, 'eu sapien cursus', 20);
insert into car (id, model, manufacturer_id) values (404, 'sapien ut', 31);
insert into car (id, model, manufacturer_id) values (405, 'mauris', 13);
insert into car (id, model, manufacturer_id) values (406, 'nibh ligula', 25);
insert into car (id, model, manufacturer_id) values (407, 'convallis tortor risus', 17);
insert into car (id, model, manufacturer_id) values (408, 'eleifend luctus ultricies', 10);
insert into car (id, model, manufacturer_id) values (409, 'pellentesque', 70);
insert into car (id, model, manufacturer_id) values (410, 'justo', 45);
insert into car (id, model, manufacturer_id) values (411, 'nulla elit ac', 35);
insert into car (id, model, manufacturer_id) values (412, 'quis turpis', 16);
insert into car (id, model, manufacturer_id) values (413, 'nullam', 52);
insert into car (id, model, manufacturer_id) values (414, 'tortor duis', 38);
insert into car (id, model, manufacturer_id) values (415, 'molestie lorem', 97);
insert into car (id, model, manufacturer_id) values (416, 'duis mattis egestas', 95);
insert into car (id, model, manufacturer_id) values (417, 'pede lobortis ligula', 8);
insert into car (id, model, manufacturer_id) values (418, 'hac', 83);
insert into car (id, model, manufacturer_id) values (419, 'quis turpis sed', 65);
insert into car (id, model, manufacturer_id) values (420, 'nullam', 55);
insert into car (id, model, manufacturer_id) values (421, 'vitae ipsum aliquam', 20);
insert into car (id, model, manufacturer_id) values (422, 'integer non', 84);
insert into car (id, model, manufacturer_id) values (423, 'nulla', 30);
insert into car (id, model, manufacturer_id) values (424, 'vulputate justo in', 30);
insert into car (id, model, manufacturer_id) values (425, 'eget eleifend', 30);
insert into car (id, model, manufacturer_id) values (426, 'justo eu', 73);
insert into car (id, model, manufacturer_id) values (427, 'tortor', 1);
insert into car (id, model, manufacturer_id) values (428, 'sed ante vivamus', 10);
insert into car (id, model, manufacturer_id) values (429, 'in', 19);
insert into car (id, model, manufacturer_id) values (430, 'vitae nisl aenean', 8);
insert into car (id, model, manufacturer_id) values (431, 'odio', 15);
insert into car (id, model, manufacturer_id) values (432, 'vitae mattis', 12);
insert into car (id, model, manufacturer_id) values (433, 'fermentum', 100);
insert into car (id, model, manufacturer_id) values (434, 'posuere felis sed', 29);
insert into car (id, model, manufacturer_id) values (435, 'turpis', 1);
insert into car (id, model, manufacturer_id) values (436, 'purus', 90);
insert into car (id, model, manufacturer_id) values (437, 'ultrices', 77);
insert into car (id, model, manufacturer_id) values (438, 'cubilia curae', 94);
insert into car (id, model, manufacturer_id) values (439, 'non interdum in', 100);
insert into car (id, model, manufacturer_id) values (440, 'erat', 82);
insert into car (id, model, manufacturer_id) values (441, 'nulla', 24);
insert into car (id, model, manufacturer_id) values (442, 'sit amet nunc', 91);
insert into car (id, model, manufacturer_id) values (443, 'rutrum at', 83);
insert into car (id, model, manufacturer_id) values (444, 'non', 80);
insert into car (id, model, manufacturer_id) values (445, 'mauris ullamcorper purus', 4);
insert into car (id, model, manufacturer_id) values (446, 'ante', 53);
insert into car (id, model, manufacturer_id) values (447, 'leo', 79);
insert into car (id, model, manufacturer_id) values (448, 'iaculis justo', 2);
insert into car (id, model, manufacturer_id) values (449, 'non', 2);
insert into car (id, model, manufacturer_id) values (450, 'nullam orci', 71);
insert into car (id, model, manufacturer_id) values (451, 'lorem', 78);
insert into car (id, model, manufacturer_id) values (452, 'potenti nullam', 86);
insert into car (id, model, manufacturer_id) values (453, 'suspendisse potenti nullam', 34);
insert into car (id, model, manufacturer_id) values (454, 'metus', 47);
insert into car (id, model, manufacturer_id) values (455, 'accumsan odio', 100);
insert into car (id, model, manufacturer_id) values (456, 'morbi', 11);
insert into car (id, model, manufacturer_id) values (457, 'luctus cum sociis', 49);
insert into car (id, model, manufacturer_id) values (458, 'augue', 81);
insert into car (id, model, manufacturer_id) values (459, 'ante', 25);
insert into car (id, model, manufacturer_id) values (460, 'vestibulum', 24);
insert into car (id, model, manufacturer_id) values (461, 'consequat nulla', 99);
insert into car (id, model, manufacturer_id) values (462, 'leo', 36);
insert into car (id, model, manufacturer_id) values (463, 'eu', 6);
insert into car (id, model, manufacturer_id) values (464, 'scelerisque mauris', 92);
insert into car (id, model, manufacturer_id) values (465, 'faucibus orci', 65);
insert into car (id, model, manufacturer_id) values (466, 'non', 35);
insert into car (id, model, manufacturer_id) values (467, 'sed tristique in', 93);
insert into car (id, model, manufacturer_id) values (468, 'ut', 41);
insert into car (id, model, manufacturer_id) values (469, 'vitae', 50);
insert into car (id, model, manufacturer_id) values (470, 'scelerisque quam', 62);
insert into car (id, model, manufacturer_id) values (471, 'mauris non ligula', 64);
insert into car (id, model, manufacturer_id) values (472, 'aliquet', 46);
insert into car (id, model, manufacturer_id) values (473, 'ac', 70);
insert into car (id, model, manufacturer_id) values (474, 'justo eu', 28);
insert into car (id, model, manufacturer_id) values (475, 'diam', 16);
insert into car (id, model, manufacturer_id) values (476, 'nulla ut', 38);
insert into car (id, model, manufacturer_id) values (477, 'rutrum', 79);
insert into car (id, model, manufacturer_id) values (478, 'convallis nunc', 15);
insert into car (id, model, manufacturer_id) values (479, 'rhoncus', 84);
insert into car (id, model, manufacturer_id) values (480, 'erat volutpat in', 7);
insert into car (id, model, manufacturer_id) values (481, 'libero', 41);
insert into car (id, model, manufacturer_id) values (482, 'sagittis sapien', 58);
insert into car (id, model, manufacturer_id) values (483, 'etiam', 56);
insert into car (id, model, manufacturer_id) values (484, 'id justo', 90);
insert into car (id, model, manufacturer_id) values (485, 'erat', 92);
insert into car (id, model, manufacturer_id) values (486, 'condimentum', 33);
insert into car (id, model, manufacturer_id) values (487, 'turpis elementum', 75);
insert into car (id, model, manufacturer_id) values (488, 'mi in', 83);
insert into car (id, model, manufacturer_id) values (489, 'curae donec', 99);
insert into car (id, model, manufacturer_id) values (490, 'odio cras mi', 8);
insert into car (id, model, manufacturer_id) values (491, 'nulla mollis molestie', 43);
insert into car (id, model, manufacturer_id) values (492, 'ut nunc vestibulum', 44);
insert into car (id, model, manufacturer_id) values (493, 'a nibh', 54);
insert into car (id, model, manufacturer_id) values (494, 'quis orci nullam', 99);
insert into car (id, model, manufacturer_id) values (495, 'orci vehicula condimentum', 34);
insert into car (id, model, manufacturer_id) values (496, 'varius nulla facilisi', 15);
insert into car (id, model, manufacturer_id) values (497, 'metus aenean', 14);
insert into car (id, model, manufacturer_id) values (498, 'nulla sed', 8);
insert into car (id, model, manufacturer_id) values (499, 'pellentesque', 41);
insert into car (id, model, manufacturer_id) values (500, 'suspendisse accumsan tortor', 76);
insert into car (id, model, manufacturer_id) values (501, 'nisl duis', 86);
insert into car (id, model, manufacturer_id) values (502, 'consequat', 19);
insert into car (id, model, manufacturer_id) values (503, 'sapien dignissim vestibulum', 66);
insert into car (id, model, manufacturer_id) values (504, 'enim blandit mi', 85);
insert into car (id, model, manufacturer_id) values (505, 'rutrum', 27);
insert into car (id, model, manufacturer_id) values (506, 'praesent id', 22);
insert into car (id, model, manufacturer_id) values (507, 'in est risus', 74);
insert into car (id, model, manufacturer_id) values (508, 'in magna', 99);
insert into car (id, model, manufacturer_id) values (509, 'condimentum id', 7);
insert into car (id, model, manufacturer_id) values (510, 'est donec odio', 92);
insert into car (id, model, manufacturer_id) values (511, 'orci', 6);
insert into car (id, model, manufacturer_id) values (512, 'sapien non', 53);
insert into car (id, model, manufacturer_id) values (513, 'montes', 34);
insert into car (id, model, manufacturer_id) values (514, 'et ultrices posuere', 72);
insert into car (id, model, manufacturer_id) values (515, 'metus', 41);
insert into car (id, model, manufacturer_id) values (516, 'nullam', 47);
insert into car (id, model, manufacturer_id) values (517, 'condimentum curabitur', 6);
insert into car (id, model, manufacturer_id) values (518, 'suspendisse potenti', 49);
insert into car (id, model, manufacturer_id) values (519, 'rutrum', 31);
insert into car (id, model, manufacturer_id) values (520, 'velit', 22);
insert into car (id, model, manufacturer_id) values (521, 'duis faucibus accumsan', 67);
insert into car (id, model, manufacturer_id) values (522, 'integer non', 22);
insert into car (id, model, manufacturer_id) values (523, 'in faucibus', 71);
insert into car (id, model, manufacturer_id) values (524, 'nisi volutpat eleifend', 40);
insert into car (id, model, manufacturer_id) values (525, 'ut tellus nulla', 53);
insert into car (id, model, manufacturer_id) values (526, 'volutpat eleifend', 86);
insert into car (id, model, manufacturer_id) values (527, 'et', 76);
insert into car (id, model, manufacturer_id) values (528, 'maecenas tincidunt lacus', 54);
insert into car (id, model, manufacturer_id) values (529, 'mi', 62);
insert into car (id, model, manufacturer_id) values (530, 'aliquam augue quam', 25);
insert into car (id, model, manufacturer_id) values (531, 'pellentesque', 31);
insert into car (id, model, manufacturer_id) values (532, 'eget elit sodales', 95);
insert into car (id, model, manufacturer_id) values (533, 'sed nisl', 67);
insert into car (id, model, manufacturer_id) values (534, 'sagittis dui', 67);
insert into car (id, model, manufacturer_id) values (535, 'interdum venenatis turpis', 83);
insert into car (id, model, manufacturer_id) values (536, 'quis', 100);
insert into car (id, model, manufacturer_id) values (537, 'vivamus tortor', 30);
insert into car (id, model, manufacturer_id) values (538, 'sed', 93);
insert into car (id, model, manufacturer_id) values (539, 'sem', 26);
insert into car (id, model, manufacturer_id) values (540, 'vulputate vitae nisl', 16);
insert into car (id, model, manufacturer_id) values (541, 'amet diam in', 54);
insert into car (id, model, manufacturer_id) values (542, 'rhoncus dui vel', 78);
insert into car (id, model, manufacturer_id) values (543, 'tortor risus', 14);
insert into car (id, model, manufacturer_id) values (544, 'ut', 32);
insert into car (id, model, manufacturer_id) values (545, 'et', 76);
insert into car (id, model, manufacturer_id) values (546, 'nulla dapibus dolor', 6);
insert into car (id, model, manufacturer_id) values (547, 'vestibulum vestibulum', 43);
insert into car (id, model, manufacturer_id) values (548, 'ipsum primis', 93);
insert into car (id, model, manufacturer_id) values (549, 'rhoncus aliquam lacus', 67);
insert into car (id, model, manufacturer_id) values (550, 'non mi', 11);
insert into car (id, model, manufacturer_id) values (551, 'dui', 72);
insert into car (id, model, manufacturer_id) values (552, 'interdum in', 64);
insert into car (id, model, manufacturer_id) values (553, 'sapien cursus vestibulum', 85);
insert into car (id, model, manufacturer_id) values (554, 'vel', 79);
insert into car (id, model, manufacturer_id) values (555, 'nulla sed vel', 54);
insert into car (id, model, manufacturer_id) values (556, 'sit amet sem', 50);
insert into car (id, model, manufacturer_id) values (557, 'in', 56);
insert into car (id, model, manufacturer_id) values (558, 'turpis sed', 45);
insert into car (id, model, manufacturer_id) values (559, 'maecenas ut massa', 43);
insert into car (id, model, manufacturer_id) values (560, 'maecenas leo', 70);
insert into car (id, model, manufacturer_id) values (561, 'integer tincidunt ante', 99);
insert into car (id, model, manufacturer_id) values (562, 'erat nulla tempus', 37);
insert into car (id, model, manufacturer_id) values (563, 'blandit nam nulla', 17);
insert into car (id, model, manufacturer_id) values (564, 'pretium iaculis diam', 34);
insert into car (id, model, manufacturer_id) values (565, 'at', 49);
insert into car (id, model, manufacturer_id) values (566, 'commodo vulputate', 70);
insert into car (id, model, manufacturer_id) values (567, 'non mauris morbi', 93);
insert into car (id, model, manufacturer_id) values (568, 'nulla sed vel', 90);
insert into car (id, model, manufacturer_id) values (569, 'consequat', 23);
insert into car (id, model, manufacturer_id) values (570, 'dapibus at', 41);
insert into car (id, model, manufacturer_id) values (571, 'donec ut dolor', 14);
insert into car (id, model, manufacturer_id) values (572, 'risus auctor', 38);
insert into car (id, model, manufacturer_id) values (573, 'aliquam erat volutpat', 50);
insert into car (id, model, manufacturer_id) values (574, 'mi', 22);
insert into car (id, model, manufacturer_id) values (575, 'dictumst morbi vestibulum', 100);
insert into car (id, model, manufacturer_id) values (576, 'tempus vel', 6);
insert into car (id, model, manufacturer_id) values (577, 'est congue elementum', 70);
insert into car (id, model, manufacturer_id) values (578, 'quis augue luctus', 12);
insert into car (id, model, manufacturer_id) values (579, 'elit', 65);
insert into car (id, model, manufacturer_id) values (580, 'sed', 36);
insert into car (id, model, manufacturer_id) values (581, 'quam', 11);
insert into car (id, model, manufacturer_id) values (582, 'maecenas pulvinar', 19);
insert into car (id, model, manufacturer_id) values (583, 'nunc', 19);
insert into car (id, model, manufacturer_id) values (584, 'aenean auctor', 27);
insert into car (id, model, manufacturer_id) values (585, 'cubilia curae nulla', 28);
insert into car (id, model, manufacturer_id) values (586, 'vestibulum sed magna', 14);
insert into car (id, model, manufacturer_id) values (587, 'sagittis sapien', 87);
insert into car (id, model, manufacturer_id) values (588, 'diam', 66);
insert into car (id, model, manufacturer_id) values (589, 'in', 31);
insert into car (id, model, manufacturer_id) values (590, 'nullam', 12);
insert into car (id, model, manufacturer_id) values (591, 'volutpat', 31);
insert into car (id, model, manufacturer_id) values (592, 'donec dapibus', 88);
insert into car (id, model, manufacturer_id) values (593, 'eget', 18);
insert into car (id, model, manufacturer_id) values (594, 'commodo vulputate', 61);
insert into car (id, model, manufacturer_id) values (595, 'pellentesque viverra pede', 56);
insert into car (id, model, manufacturer_id) values (596, 'felis ut', 86);
insert into car (id, model, manufacturer_id) values (597, 'sapien cum', 31);
insert into car (id, model, manufacturer_id) values (598, 'amet diam', 65);
insert into car (id, model, manufacturer_id) values (599, 'tellus', 79);
insert into car (id, model, manufacturer_id) values (600, 'luctus rutrum nulla', 12);
insert into car (id, model, manufacturer_id) values (601, 'posuere felis', 66);
insert into car (id, model, manufacturer_id) values (602, 'iaculis congue', 93);
insert into car (id, model, manufacturer_id) values (603, 'eget massa', 57);
insert into car (id, model, manufacturer_id) values (604, 'curabitur', 27);
insert into car (id, model, manufacturer_id) values (605, 'ultricies eu nibh', 89);
insert into car (id, model, manufacturer_id) values (606, 'erat tortor', 99);
insert into car (id, model, manufacturer_id) values (607, 'pede ullamcorper augue', 33);
insert into car (id, model, manufacturer_id) values (608, 'pulvinar nulla', 34);
insert into car (id, model, manufacturer_id) values (609, 'odio', 45);
insert into car (id, model, manufacturer_id) values (610, 'in congue etiam', 85);
insert into car (id, model, manufacturer_id) values (611, 'erat id mauris', 44);
insert into car (id, model, manufacturer_id) values (612, 'ante vel ipsum', 32);
insert into car (id, model, manufacturer_id) values (613, 'nunc nisl', 36);
insert into car (id, model, manufacturer_id) values (614, 'lacus morbi', 19);
insert into car (id, model, manufacturer_id) values (615, 'enim', 39);
insert into car (id, model, manufacturer_id) values (616, 'nulla pede ullamcorper', 24);
insert into car (id, model, manufacturer_id) values (617, 'vitae ipsum', 3);
insert into car (id, model, manufacturer_id) values (618, 'faucibus', 89);
insert into car (id, model, manufacturer_id) values (619, 'felis sed', 28);
insert into car (id, model, manufacturer_id) values (620, 'dolor quis', 25);
insert into car (id, model, manufacturer_id) values (621, 'elementum ligula', 33);
insert into car (id, model, manufacturer_id) values (622, 'diam cras', 86);
insert into car (id, model, manufacturer_id) values (623, 'nisl', 23);
insert into car (id, model, manufacturer_id) values (624, 'id', 18);
insert into car (id, model, manufacturer_id) values (625, 'hendrerit at', 22);
insert into car (id, model, manufacturer_id) values (626, 'nullam porttitor lacus', 20);
insert into car (id, model, manufacturer_id) values (627, 'natoque', 61);
insert into car (id, model, manufacturer_id) values (628, 'a feugiat', 67);
insert into car (id, model, manufacturer_id) values (629, 'ipsum', 76);
insert into car (id, model, manufacturer_id) values (630, 'et', 1);
insert into car (id, model, manufacturer_id) values (631, 'mi in porttitor', 80);
insert into car (id, model, manufacturer_id) values (632, 'orci', 27);
insert into car (id, model, manufacturer_id) values (633, 'aliquet', 52);
insert into car (id, model, manufacturer_id) values (634, 'a pede posuere', 30);
insert into car (id, model, manufacturer_id) values (635, 'eget congue eget', 93);
insert into car (id, model, manufacturer_id) values (636, 'vel pede', 60);
insert into car (id, model, manufacturer_id) values (637, 'dui luctus rutrum', 29);
insert into car (id, model, manufacturer_id) values (638, 'pretium', 33);
insert into car (id, model, manufacturer_id) values (639, 'ante vel', 60);
insert into car (id, model, manufacturer_id) values (640, 'porttitor lacus', 41);
insert into car (id, model, manufacturer_id) values (641, 'convallis eget eleifend', 28);
insert into car (id, model, manufacturer_id) values (642, 'sit', 97);
insert into car (id, model, manufacturer_id) values (643, 'id', 66);
insert into car (id, model, manufacturer_id) values (644, 'ut tellus nulla', 96);
insert into car (id, model, manufacturer_id) values (645, 'turpis sed ante', 31);
insert into car (id, model, manufacturer_id) values (646, 'quis', 19);
insert into car (id, model, manufacturer_id) values (647, 'diam', 26);
insert into car (id, model, manufacturer_id) values (648, 'id luctus', 54);
insert into car (id, model, manufacturer_id) values (649, 'ligula in', 43);
insert into car (id, model, manufacturer_id) values (650, 'est phasellus sit', 96);
insert into car (id, model, manufacturer_id) values (651, 'cras mi pede', 97);
insert into car (id, model, manufacturer_id) values (652, 'velit vivamus vel', 25);
insert into car (id, model, manufacturer_id) values (653, 'donec odio', 24);
insert into car (id, model, manufacturer_id) values (654, 'eget eros elementum', 14);
insert into car (id, model, manufacturer_id) values (655, 'adipiscing', 78);
insert into car (id, model, manufacturer_id) values (656, 'libero nam', 53);
insert into car (id, model, manufacturer_id) values (657, 'nec', 53);
insert into car (id, model, manufacturer_id) values (658, 'morbi', 17);
insert into car (id, model, manufacturer_id) values (659, 'ac est', 17);
insert into car (id, model, manufacturer_id) values (660, 'ante ipsum', 37);
insert into car (id, model, manufacturer_id) values (661, 'pellentesque ultrices', 94);
insert into car (id, model, manufacturer_id) values (662, 'id turpis', 1);
insert into car (id, model, manufacturer_id) values (663, 'neque vestibulum eget', 23);
insert into car (id, model, manufacturer_id) values (664, 'sed tincidunt eu', 92);
insert into car (id, model, manufacturer_id) values (665, 'duis ac', 32);
insert into car (id, model, manufacturer_id) values (666, 'penatibus et', 68);
insert into car (id, model, manufacturer_id) values (667, 'pellentesque ultrices', 25);
insert into car (id, model, manufacturer_id) values (668, 'eget', 18);
insert into car (id, model, manufacturer_id) values (669, 'turpis eget elit', 48);
insert into car (id, model, manufacturer_id) values (670, 'pede ullamcorper', 50);
insert into car (id, model, manufacturer_id) values (671, 'lorem quisque ut', 67);
insert into car (id, model, manufacturer_id) values (672, 'augue quam', 53);
insert into car (id, model, manufacturer_id) values (673, 'ipsum dolor sit', 30);
insert into car (id, model, manufacturer_id) values (674, 'fermentum justo', 43);
insert into car (id, model, manufacturer_id) values (675, 'non', 15);
insert into car (id, model, manufacturer_id) values (676, 'bibendum morbi non', 93);
insert into car (id, model, manufacturer_id) values (677, 'habitasse platea dictumst', 66);
insert into car (id, model, manufacturer_id) values (678, 'arcu', 53);
insert into car (id, model, manufacturer_id) values (679, 'congue risus semper', 23);
insert into car (id, model, manufacturer_id) values (680, 'lacinia aenean', 79);
insert into car (id, model, manufacturer_id) values (681, 'ut', 92);
insert into car (id, model, manufacturer_id) values (682, 'sed lacus morbi', 38);
insert into car (id, model, manufacturer_id) values (683, 'congue eget semper', 35);
insert into car (id, model, manufacturer_id) values (684, 'orci eget', 85);
insert into car (id, model, manufacturer_id) values (685, 'amet justo morbi', 49);
insert into car (id, model, manufacturer_id) values (686, 'augue a suscipit', 81);
insert into car (id, model, manufacturer_id) values (687, 'est quam', 18);
insert into car (id, model, manufacturer_id) values (688, 'penatibus et magnis', 54);
insert into car (id, model, manufacturer_id) values (689, 'in faucibus', 18);
insert into car (id, model, manufacturer_id) values (690, 'quam', 38);
insert into car (id, model, manufacturer_id) values (691, 'magna', 37);
insert into car (id, model, manufacturer_id) values (692, 'metus sapien', 55);
insert into car (id, model, manufacturer_id) values (693, 'morbi quis tortor', 4);
insert into car (id, model, manufacturer_id) values (694, 'vestibulum', 69);
insert into car (id, model, manufacturer_id) values (695, 'ante', 59);
insert into car (id, model, manufacturer_id) values (696, 'habitasse platea', 12);
insert into car (id, model, manufacturer_id) values (697, 'ultrices posuere cubilia', 54);
insert into car (id, model, manufacturer_id) values (698, 'faucibus orci luctus', 63);
insert into car (id, model, manufacturer_id) values (699, 'curae nulla dapibus', 75);
insert into car (id, model, manufacturer_id) values (700, 'lectus in', 40);
insert into car (id, model, manufacturer_id) values (701, 'eleifend donec', 58);
insert into car (id, model, manufacturer_id) values (702, 'magnis dis', 89);
insert into car (id, model, manufacturer_id) values (703, 'nec', 82);
insert into car (id, model, manufacturer_id) values (704, 'lorem ipsum', 79);
insert into car (id, model, manufacturer_id) values (705, 'quis', 75);
insert into car (id, model, manufacturer_id) values (706, 'vel', 11);
insert into car (id, model, manufacturer_id) values (707, 'viverra dapibus', 28);
insert into car (id, model, manufacturer_id) values (708, 'odio in hac', 43);
insert into car (id, model, manufacturer_id) values (709, 'mauris enim', 47);
insert into car (id, model, manufacturer_id) values (710, 'sit', 52);
insert into car (id, model, manufacturer_id) values (711, 'nisi vulputate nonummy', 31);
insert into car (id, model, manufacturer_id) values (712, 'in faucibus orci', 40);
insert into car (id, model, manufacturer_id) values (713, 'consequat', 36);
insert into car (id, model, manufacturer_id) values (714, 'luctus', 88);
insert into car (id, model, manufacturer_id) values (715, 'ultrices vel', 37);
insert into car (id, model, manufacturer_id) values (716, 'a', 49);
insert into car (id, model, manufacturer_id) values (717, 'eros viverra eget', 4);
insert into car (id, model, manufacturer_id) values (718, 'quam fringilla rhoncus', 90);
insert into car (id, model, manufacturer_id) values (719, 'pretium iaculis', 29);
insert into car (id, model, manufacturer_id) values (720, 'sit', 52);
insert into car (id, model, manufacturer_id) values (721, 'ornare imperdiet sapien', 12);
insert into car (id, model, manufacturer_id) values (722, 'vel enim sit', 15);
insert into car (id, model, manufacturer_id) values (723, 'quisque', 65);
insert into car (id, model, manufacturer_id) values (724, 'nunc', 37);
insert into car (id, model, manufacturer_id) values (725, 'ante', 16);
insert into car (id, model, manufacturer_id) values (726, 'eget', 31);
insert into car (id, model, manufacturer_id) values (727, 'aliquet pulvinar', 74);
insert into car (id, model, manufacturer_id) values (728, 'faucibus orci', 79);
insert into car (id, model, manufacturer_id) values (729, 'molestie hendrerit', 56);
insert into car (id, model, manufacturer_id) values (730, 'cursus vestibulum proin', 12);
insert into car (id, model, manufacturer_id) values (731, 'sodales', 38);
insert into car (id, model, manufacturer_id) values (732, 'dolor sit', 1);
insert into car (id, model, manufacturer_id) values (733, 'quis', 13);
insert into car (id, model, manufacturer_id) values (734, 'ac', 24);
insert into car (id, model, manufacturer_id) values (735, 'quam', 94);
insert into car (id, model, manufacturer_id) values (736, 'curabitur', 63);
insert into car (id, model, manufacturer_id) values (737, 'placerat ante nulla', 96);
insert into car (id, model, manufacturer_id) values (738, 'orci luctus et', 39);
insert into car (id, model, manufacturer_id) values (739, 'purus aliquet at', 38);
insert into car (id, model, manufacturer_id) values (740, 'sed magna at', 53);
insert into car (id, model, manufacturer_id) values (741, 'imperdiet', 88);
insert into car (id, model, manufacturer_id) values (742, 'malesuada in imperdiet', 15);
insert into car (id, model, manufacturer_id) values (743, 'arcu', 13);
insert into car (id, model, manufacturer_id) values (744, 'sit amet consectetuer', 23);
insert into car (id, model, manufacturer_id) values (745, 'et ultrices posuere', 58);
insert into car (id, model, manufacturer_id) values (746, 'et ultrices posuere', 38);
insert into car (id, model, manufacturer_id) values (747, 'tellus semper', 39);
insert into car (id, model, manufacturer_id) values (748, 'eu mi', 60);
insert into car (id, model, manufacturer_id) values (749, 'ut ultrices', 63);
insert into car (id, model, manufacturer_id) values (750, 'vestibulum ante', 41);
insert into car (id, model, manufacturer_id) values (751, 'pede', 25);
insert into car (id, model, manufacturer_id) values (752, 'ut nunc vestibulum', 94);
insert into car (id, model, manufacturer_id) values (753, 'iaculis justo', 86);
insert into car (id, model, manufacturer_id) values (754, 'quis odio consequat', 68);
insert into car (id, model, manufacturer_id) values (755, 'natoque penatibus', 87);
insert into car (id, model, manufacturer_id) values (756, 'sed lacus morbi', 22);
insert into car (id, model, manufacturer_id) values (757, 'nulla sed vel', 53);
insert into car (id, model, manufacturer_id) values (758, 'et ultrices posuere', 47);
insert into car (id, model, manufacturer_id) values (759, 'amet', 66);
insert into car (id, model, manufacturer_id) values (760, 'sit amet', 73);
insert into car (id, model, manufacturer_id) values (761, 'nulla ac', 49);
insert into car (id, model, manufacturer_id) values (762, 'eget tempus vel', 50);
insert into car (id, model, manufacturer_id) values (763, 'purus aliquet', 23);
insert into car (id, model, manufacturer_id) values (764, 'ipsum ac', 23);
insert into car (id, model, manufacturer_id) values (765, 'luctus rutrum nulla', 81);
insert into car (id, model, manufacturer_id) values (766, 'in', 77);
insert into car (id, model, manufacturer_id) values (767, 'habitasse platea dictumst', 69);
insert into car (id, model, manufacturer_id) values (768, 'pulvinar sed nisl', 15);
insert into car (id, model, manufacturer_id) values (769, 'erat eros viverra', 46);
insert into car (id, model, manufacturer_id) values (770, 'quam fringilla', 92);
insert into car (id, model, manufacturer_id) values (771, 'pharetra magna', 39);
insert into car (id, model, manufacturer_id) values (772, 'vivamus', 32);
insert into car (id, model, manufacturer_id) values (773, 'amet', 81);
insert into car (id, model, manufacturer_id) values (774, 'orci', 21);
insert into car (id, model, manufacturer_id) values (775, 'ut suscipit a', 38);
insert into car (id, model, manufacturer_id) values (776, 'elementum ligula', 20);
insert into car (id, model, manufacturer_id) values (777, 'turpis nec', 23);
insert into car (id, model, manufacturer_id) values (778, 'interdum', 30);
insert into car (id, model, manufacturer_id) values (779, 'vulputate justo', 54);
insert into car (id, model, manufacturer_id) values (780, 'venenatis', 21);
insert into car (id, model, manufacturer_id) values (781, 'vestibulum aliquet ultrices', 46);
insert into car (id, model, manufacturer_id) values (782, 'id luctus', 30);
insert into car (id, model, manufacturer_id) values (783, 'donec diam neque', 99);
insert into car (id, model, manufacturer_id) values (784, 'ut', 42);
insert into car (id, model, manufacturer_id) values (785, 'felis', 64);
insert into car (id, model, manufacturer_id) values (786, 'diam id ornare', 29);
insert into car (id, model, manufacturer_id) values (787, 'nisi venenatis tristique', 16);
insert into car (id, model, manufacturer_id) values (788, 'aliquet massa', 69);
insert into car (id, model, manufacturer_id) values (789, 'vel sem sed', 97);
insert into car (id, model, manufacturer_id) values (790, 'cum sociis', 57);
insert into car (id, model, manufacturer_id) values (791, 'non', 67);
insert into car (id, model, manufacturer_id) values (792, 'faucibus', 100);
insert into car (id, model, manufacturer_id) values (793, 'consequat varius integer', 88);
insert into car (id, model, manufacturer_id) values (794, 'in porttitor pede', 9);
insert into car (id, model, manufacturer_id) values (795, 'ligula sit amet', 30);
insert into car (id, model, manufacturer_id) values (796, 'eu', 48);
insert into car (id, model, manufacturer_id) values (797, 'dictumst', 48);
insert into car (id, model, manufacturer_id) values (798, 'odio curabitur', 94);
insert into car (id, model, manufacturer_id) values (799, 'consequat', 30);
insert into car (id, model, manufacturer_id) values (800, 'nulla integer pede', 7);
insert into car (id, model, manufacturer_id) values (801, 'eu orci', 11);
insert into car (id, model, manufacturer_id) values (802, 'turpis adipiscing lorem', 63);
insert into car (id, model, manufacturer_id) values (803, 'porta volutpat quam', 18);
insert into car (id, model, manufacturer_id) values (804, 'est lacinia', 17);
insert into car (id, model, manufacturer_id) values (805, 'proin', 56);
insert into car (id, model, manufacturer_id) values (806, 'nulla facilisi cras', 9);
insert into car (id, model, manufacturer_id) values (807, 'vitae nisi', 98);
insert into car (id, model, manufacturer_id) values (808, 'ac nulla sed', 88);
insert into car (id, model, manufacturer_id) values (809, 'volutpat in', 83);
insert into car (id, model, manufacturer_id) values (810, 'nisi at', 72);
insert into car (id, model, manufacturer_id) values (811, 'eget vulputate ut', 35);
insert into car (id, model, manufacturer_id) values (812, 'elementum', 63);
insert into car (id, model, manufacturer_id) values (813, 'sit', 80);
insert into car (id, model, manufacturer_id) values (814, 'posuere cubilia', 1);
insert into car (id, model, manufacturer_id) values (815, 'id', 51);
insert into car (id, model, manufacturer_id) values (816, 'in tempus sit', 8);
insert into car (id, model, manufacturer_id) values (817, 'nisi venenatis', 87);
insert into car (id, model, manufacturer_id) values (818, 'vestibulum', 53);
insert into car (id, model, manufacturer_id) values (819, 'quam pharetra magna', 76);
insert into car (id, model, manufacturer_id) values (820, 'mauris ullamcorper', 34);
insert into car (id, model, manufacturer_id) values (821, 'id sapien in', 81);
insert into car (id, model, manufacturer_id) values (822, 'viverra', 66);
insert into car (id, model, manufacturer_id) values (823, 'vulputate vitae', 18);
insert into car (id, model, manufacturer_id) values (824, 'lorem vitae', 49);
insert into car (id, model, manufacturer_id) values (825, 'orci vehicula condimentum', 94);
insert into car (id, model, manufacturer_id) values (826, 'ipsum ac', 28);
insert into car (id, model, manufacturer_id) values (827, 'potenti cras', 96);
insert into car (id, model, manufacturer_id) values (828, 'vestibulum', 80);
insert into car (id, model, manufacturer_id) values (829, 'diam nam tristique', 84);
insert into car (id, model, manufacturer_id) values (830, 'purus sit', 99);
insert into car (id, model, manufacturer_id) values (831, 'nascetur ridiculus mus', 43);
insert into car (id, model, manufacturer_id) values (832, 'volutpat', 29);
insert into car (id, model, manufacturer_id) values (833, 'congue diam', 76);
insert into car (id, model, manufacturer_id) values (834, 'varius ut', 28);
insert into car (id, model, manufacturer_id) values (835, 'libero ut massa', 80);
insert into car (id, model, manufacturer_id) values (836, 'amet', 13);
insert into car (id, model, manufacturer_id) values (837, 'ipsum primis', 90);
insert into car (id, model, manufacturer_id) values (838, 'ut erat curabitur', 66);
insert into car (id, model, manufacturer_id) values (839, 'lectus aliquam sit', 31);
insert into car (id, model, manufacturer_id) values (840, 'ut', 99);
insert into car (id, model, manufacturer_id) values (841, 'vestibulum rutrum rutrum', 75);
insert into car (id, model, manufacturer_id) values (842, 'amet turpis', 96);
insert into car (id, model, manufacturer_id) values (843, 'integer pede', 88);
insert into car (id, model, manufacturer_id) values (844, 'enim leo rhoncus', 45);
insert into car (id, model, manufacturer_id) values (845, 'semper sapien a', 32);
insert into car (id, model, manufacturer_id) values (846, 'interdum venenatis', 84);
insert into car (id, model, manufacturer_id) values (847, 'elit', 8);
insert into car (id, model, manufacturer_id) values (848, 'etiam', 10);
insert into car (id, model, manufacturer_id) values (849, 'vestibulum', 23);
insert into car (id, model, manufacturer_id) values (850, 'maecenas rhoncus aliquam', 35);
insert into car (id, model, manufacturer_id) values (851, 'imperdiet et', 52);
insert into car (id, model, manufacturer_id) values (852, 'maecenas', 21);
insert into car (id, model, manufacturer_id) values (853, 'accumsan tortor', 76);
insert into car (id, model, manufacturer_id) values (854, 'vulputate', 67);
insert into car (id, model, manufacturer_id) values (855, 'nam congue risus', 74);
insert into car (id, model, manufacturer_id) values (856, 'a feugiat', 61);
insert into car (id, model, manufacturer_id) values (857, 'ac est', 92);
insert into car (id, model, manufacturer_id) values (858, 'at diam', 38);
insert into car (id, model, manufacturer_id) values (859, 'elementum', 15);
insert into car (id, model, manufacturer_id) values (860, 'lorem integer', 72);
insert into car (id, model, manufacturer_id) values (861, 'tortor', 21);
insert into car (id, model, manufacturer_id) values (862, 'vulputate vitae nisl', 83);
insert into car (id, model, manufacturer_id) values (863, 'tellus semper interdum', 34);
insert into car (id, model, manufacturer_id) values (864, 'a nibh', 63);
insert into car (id, model, manufacturer_id) values (865, 'ligula', 52);
insert into car (id, model, manufacturer_id) values (866, 'et ultrices', 42);
insert into car (id, model, manufacturer_id) values (867, 'cubilia curae donec', 69);
insert into car (id, model, manufacturer_id) values (868, 'ipsum primis', 57);
insert into car (id, model, manufacturer_id) values (869, 'nisi', 54);
insert into car (id, model, manufacturer_id) values (870, 'luctus', 41);
insert into car (id, model, manufacturer_id) values (871, 'cras pellentesque volutpat', 71);
insert into car (id, model, manufacturer_id) values (872, 'nibh in', 51);
insert into car (id, model, manufacturer_id) values (873, 'nunc viverra', 89);
insert into car (id, model, manufacturer_id) values (874, 'lectus vestibulum quam', 64);
insert into car (id, model, manufacturer_id) values (875, 'ac', 51);
insert into car (id, model, manufacturer_id) values (876, 'integer', 97);
insert into car (id, model, manufacturer_id) values (877, 'id', 65);
insert into car (id, model, manufacturer_id) values (878, 'turpis eget elit', 38);
insert into car (id, model, manufacturer_id) values (879, 'nam', 21);
insert into car (id, model, manufacturer_id) values (880, 'sapien arcu', 23);
insert into car (id, model, manufacturer_id) values (881, 'eget', 56);
insert into car (id, model, manufacturer_id) values (882, 'nunc rhoncus dui', 15);
insert into car (id, model, manufacturer_id) values (883, 'porttitor lorem', 21);
insert into car (id, model, manufacturer_id) values (884, 'suspendisse potenti nullam', 18);
insert into car (id, model, manufacturer_id) values (885, 'eleifend donec', 26);
insert into car (id, model, manufacturer_id) values (886, 'pulvinar', 59);
insert into car (id, model, manufacturer_id) values (887, 'lobortis est', 60);
insert into car (id, model, manufacturer_id) values (888, 'elit', 73);
insert into car (id, model, manufacturer_id) values (889, 'pellentesque', 48);
insert into car (id, model, manufacturer_id) values (890, 'magna', 19);
insert into car (id, model, manufacturer_id) values (891, 'sed', 2);
insert into car (id, model, manufacturer_id) values (892, 'in faucibus orci', 77);
insert into car (id, model, manufacturer_id) values (893, 'fusce congue', 76);
insert into car (id, model, manufacturer_id) values (894, 'donec', 27);
insert into car (id, model, manufacturer_id) values (895, 'nonummy maecenas', 45);
insert into car (id, model, manufacturer_id) values (896, 'penatibus et', 94);
insert into car (id, model, manufacturer_id) values (897, 'nec nisi vulputate', 94);
insert into car (id, model, manufacturer_id) values (898, 'semper sapien a', 56);
insert into car (id, model, manufacturer_id) values (899, 'diam nam tristique', 28);
insert into car (id, model, manufacturer_id) values (900, 'mattis pulvinar nulla', 13);
insert into car (id, model, manufacturer_id) values (901, 'vel accumsan tellus', 11);
insert into car (id, model, manufacturer_id) values (902, 'eget', 43);
insert into car (id, model, manufacturer_id) values (903, 'nulla integer', 19);
insert into car (id, model, manufacturer_id) values (904, 'lobortis ligula', 77);
insert into car (id, model, manufacturer_id) values (905, 'eget', 6);
insert into car (id, model, manufacturer_id) values (906, 'et', 86);
insert into car (id, model, manufacturer_id) values (907, 'eu massa donec', 66);
insert into car (id, model, manufacturer_id) values (908, 'tincidunt eu', 11);
insert into car (id, model, manufacturer_id) values (909, 'mi', 19);
insert into car (id, model, manufacturer_id) values (910, 'libero', 77);
insert into car (id, model, manufacturer_id) values (911, 'fusce', 40);
insert into car (id, model, manufacturer_id) values (912, 'nullam varius', 21);
insert into car (id, model, manufacturer_id) values (913, 'sed augue aliquam', 35);
insert into car (id, model, manufacturer_id) values (914, 'ac lobortis', 91);
insert into car (id, model, manufacturer_id) values (915, 'mauris lacinia', 78);
insert into car (id, model, manufacturer_id) values (916, 'convallis eget', 91);
insert into car (id, model, manufacturer_id) values (917, 'hendrerit', 51);
insert into car (id, model, manufacturer_id) values (918, 'lobortis', 55);
insert into car (id, model, manufacturer_id) values (919, 'nulla ac enim', 11);
insert into car (id, model, manufacturer_id) values (920, 'non lectus', 78);
insert into car (id, model, manufacturer_id) values (921, 'in lacus curabitur', 48);
insert into car (id, model, manufacturer_id) values (922, 'ut suscipit', 1);
insert into car (id, model, manufacturer_id) values (923, 'consequat', 16);
insert into car (id, model, manufacturer_id) values (924, 'eleifend donec ut', 68);
insert into car (id, model, manufacturer_id) values (925, 'sapien', 95);
insert into car (id, model, manufacturer_id) values (926, 'et', 98);
insert into car (id, model, manufacturer_id) values (927, 'nulla', 1);
insert into car (id, model, manufacturer_id) values (928, 'nisi venenatis tristique', 3);
insert into car (id, model, manufacturer_id) values (929, 'vestibulum ante ipsum', 86);
insert into car (id, model, manufacturer_id) values (930, 'eget rutrum at', 56);
insert into car (id, model, manufacturer_id) values (931, 'amet cursus id', 83);
insert into car (id, model, manufacturer_id) values (932, 'pharetra magna vestibulum', 95);
insert into car (id, model, manufacturer_id) values (933, 'ridiculus', 68);
insert into car (id, model, manufacturer_id) values (934, 'quisque porta', 47);
insert into car (id, model, manufacturer_id) values (935, 'aenean lectus', 83);
insert into car (id, model, manufacturer_id) values (936, 'accumsan felis ut', 58);
insert into car (id, model, manufacturer_id) values (937, 'et ultrices posuere', 33);
insert into car (id, model, manufacturer_id) values (938, 'id', 59);
insert into car (id, model, manufacturer_id) values (939, 'nibh', 56);
insert into car (id, model, manufacturer_id) values (940, 'at lorem', 25);
insert into car (id, model, manufacturer_id) values (941, 'odio', 65);
insert into car (id, model, manufacturer_id) values (942, 'a nibh', 70);
insert into car (id, model, manufacturer_id) values (943, 'in hac', 71);
insert into car (id, model, manufacturer_id) values (944, 'et ultrices posuere', 53);
insert into car (id, model, manufacturer_id) values (945, 'dignissim', 50);
insert into car (id, model, manufacturer_id) values (946, 'lectus', 15);
insert into car (id, model, manufacturer_id) values (947, 'justo in hac', 49);
insert into car (id, model, manufacturer_id) values (948, 'nulla ac', 40);
insert into car (id, model, manufacturer_id) values (949, 'natoque', 78);
insert into car (id, model, manufacturer_id) values (950, 'sed vestibulum sit', 95);
insert into car (id, model, manufacturer_id) values (951, 'turpis', 45);
insert into car (id, model, manufacturer_id) values (952, 'non sodales', 65);
insert into car (id, model, manufacturer_id) values (953, 'morbi quis tortor', 67);
insert into car (id, model, manufacturer_id) values (954, 'faucibus cursus urna', 17);
insert into car (id, model, manufacturer_id) values (955, 'accumsan tortor', 26);
insert into car (id, model, manufacturer_id) values (956, 'consequat in consequat', 38);
insert into car (id, model, manufacturer_id) values (957, 'ut', 54);
insert into car (id, model, manufacturer_id) values (958, 'non interdum', 30);
insert into car (id, model, manufacturer_id) values (959, 'in ante', 64);
insert into car (id, model, manufacturer_id) values (960, 'in hac habitasse', 33);
insert into car (id, model, manufacturer_id) values (961, 'suscipit', 56);
insert into car (id, model, manufacturer_id) values (962, 'at', 22);
insert into car (id, model, manufacturer_id) values (963, 'pellentesque quisque porta', 44);
insert into car (id, model, manufacturer_id) values (964, 'pretium', 68);
insert into car (id, model, manufacturer_id) values (965, 'purus sit', 22);
insert into car (id, model, manufacturer_id) values (966, 'habitasse platea', 6);
insert into car (id, model, manufacturer_id) values (967, 'convallis', 3);
insert into car (id, model, manufacturer_id) values (968, 'ante', 65);
insert into car (id, model, manufacturer_id) values (969, 'eros vestibulum', 11);
insert into car (id, model, manufacturer_id) values (970, 'ligula', 79);
insert into car (id, model, manufacturer_id) values (971, 'et commodo', 25);
insert into car (id, model, manufacturer_id) values (972, 'molestie', 3);
insert into car (id, model, manufacturer_id) values (973, 'quis', 31);
insert into car (id, model, manufacturer_id) values (974, 'quis libero', 40);
insert into car (id, model, manufacturer_id) values (975, 'sapien dignissim vestibulum', 78);
insert into car (id, model, manufacturer_id) values (976, 'odio', 52);
insert into car (id, model, manufacturer_id) values (977, 'maecenas pulvinar lobortis', 77);
insert into car (id, model, manufacturer_id) values (978, 'ac', 32);
insert into car (id, model, manufacturer_id) values (979, 'non', 25);
insert into car (id, model, manufacturer_id) values (980, 'nisl aenean', 69);
insert into car (id, model, manufacturer_id) values (981, 'consequat', 99);
insert into car (id, model, manufacturer_id) values (982, 'sapien', 1);
insert into car (id, model, manufacturer_id) values (983, 'suscipit ligula in', 36);
insert into car (id, model, manufacturer_id) values (984, 'justo in', 88);
insert into car (id, model, manufacturer_id) values (985, 'sem duis', 52);
insert into car (id, model, manufacturer_id) values (986, 'eget vulputate ut', 41);
insert into car (id, model, manufacturer_id) values (987, 'in', 61);
insert into car (id, model, manufacturer_id) values (988, 'duis', 59);
insert into car (id, model, manufacturer_id) values (989, 'mollis', 53);
insert into car (id, model, manufacturer_id) values (990, 'pede justo', 83);
insert into car (id, model, manufacturer_id) values (991, 'dapibus dolor vel', 68);
insert into car (id, model, manufacturer_id) values (992, 'venenatis lacinia', 81);
insert into car (id, model, manufacturer_id) values (993, 'amet sem fusce', 4);
insert into car (id, model, manufacturer_id) values (994, 'metus vitae', 25);
insert into car (id, model, manufacturer_id) values (995, 'amet erat nulla', 44);
insert into car (id, model, manufacturer_id) values (996, 'volutpat erat', 78);
insert into car (id, model, manufacturer_id) values (997, 'sem fusce', 79);
insert into car (id, model, manufacturer_id) values (998, 'duis ac nibh', 67);
insert into car (id, model, manufacturer_id) values (999, 'turpis elementum ligula', 98);
insert into car (id, model, manufacturer_id) values (1000, 'feugiat non', 52);
